"use client";

import { useQuery } from "@tanstack/react-query";
import { CheckCircle2, ShieldCheck, ShieldX } from "lucide-react";
import { useState } from "react";
import { api } from "@/lib/api/client";
import type { EvidenceEntry } from "@/domain/types";
import { ApiUnavailable, EmptyState, LoadingState } from "@/components/ui/States";
import { PageFrame } from "../dashboard/page";

export default function EvidencePage() { const query = useQuery({ queryKey: ["evidence"], queryFn: api.evidence }); const [verified, setVerified] = useState<boolean | null>(null); return <PageFrame eyebrow="Compliance trace" title="An append-only evidence sketch" detail="This is a tamper-evident demonstration, not a replacement for a regulatory ledger.">{query.isLoading ? <LoadingState label="Loading decision evidence"/> : query.isError ? <ApiUnavailable onRetry={() => query.refetch()} /> : <section className="data-panel evidence-panel"><header className="evidence-header"><div><p className="eyebrow">Backend supplied decision log</p><h2>Hash chain</h2></div><button className="button primary" onClick={async () => setVerified(await verifyChain(query.data ?? []))}>{verified === true ? <CheckCircle2 size={16}/> : verified === false ? <ShieldX size={16}/> : <ShieldCheck size={16}/>} {verified === null ? "Verify chain" : verified ? "Chain verified" : "Mismatch found"}</button></header>{query.data?.length ? <EvidenceTable rows={query.data} invalid={verified === false} /> : <EmptyState title="No evidence entries yet." detail="Entries appear when an operator acknowledges, reassigns, exports, notes, or escalates a backend record." />}</section>}</PageFrame>; }

async function sha256(value: string) { const bytes = new TextEncoder().encode(value); const hash = await crypto.subtle.digest("SHA-256", bytes); return Array.from(new Uint8Array(hash)).map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
async function verifyChain(rows: EvidenceEntry[]) { let previous = "0".repeat(64); for (const row of rows) { const payload = { action: row.action, agent: row.agent, index: row.index, note: row.note, refId: row.refId, refType: row.refType, ts: row.ts }; const canonical = JSON.stringify(payload, Object.keys(payload).sort()); if (row.prevHash !== previous || row.hash !== await sha256(`${previous}${canonical}`)) return false; previous = row.hash; } return true; }
function EvidenceTable({ rows, invalid }: { rows: EvidenceEntry[]; invalid: boolean }) { return <div className="table-wrap"><table className="standard-table evidence-table"><thead><tr><th>Index</th><th>Timestamp</th><th>Agent</th><th>Action</th><th>Reference</th><th>Hash</th><th>Previous hash</th></tr></thead><tbody>{rows.map((row) => <tr className={invalid ? "invalid" : ""} key={`${row.index}-${row.hash}`}><td>{row.index}</td><td>{new Date(row.ts).toUTCString()}</td><td>{row.agent}</td><td>{row.action}</td><td>{row.refType} · {row.refId}</td><td><code>{row.hash}</code></td><td><code>{row.prevHash}</code></td></tr>)}</tbody></table></div>; }
