"use client";

import { useInfiniteQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Activity, Check, ChevronDown, Download, ShieldAlert } from "lucide-react";
import { api } from "@/lib/api/client";
import type { Anomaly } from "@/domain/types";
import { ApiUnavailable, EmptyState, LoadingState } from "@/components/ui/States";
import { PageFrame } from "../dashboard/page";
import { useState } from "react";

export default function AnomaliesPage() { const [selected, setSelected] = useState<Anomaly | null>(null); const client = useQueryClient(); const query = useInfiniteQuery({ queryKey: ["anomalies"], queryFn: ({ pageParam }) => api.anomalies(pageParam), initialPageParam: undefined as string | undefined, getNextPageParam: (last) => last.nextCursor }); const acknowledge = useMutation({ mutationFn: api.acknowledge, onSuccess: () => client.invalidateQueries({ queryKey: ["anomalies"] }) }); const anomalies = query.data?.pages.flatMap((page) => page.items) ?? []; return <PageFrame eyebrow="Compliance review" title="Patterns surfaced for human review" detail="A high score is not a finding. Final responsibility rests with the compliance team and the regulator.">{query.isLoading ? <LoadingState label="Loading anomaly feed"/> : query.isError ? <ApiUnavailable onRetry={() => query.refetch()} /> : <div className="anomaly-layout"><section className="data-panel anomaly-feed"><header className="feed-toolbar"><div><p className="eyebrow">Ranked by backend score</p><h2>Open anomaly feed</h2></div><span>{anomalies.length} loaded</span></header>{anomalies.length ? anomalies.map((item) => <button className={`anomaly-row ${selected?.id === item.id ? "selected" : ""}`} key={item.id} onClick={() => setSelected(item)}><span className={`severity-mark ${item.severity}`}><Activity size={17}/></span><div><strong>{item.kind.replaceAll("_", " ")}</strong><p>{item.providerId} · {item.corridor} · opened {new Date(item.openedAt).toUTCString()}</p></div><b>{item.score}</b><ChevronDown size={16}/></button>) : <EmptyState title="No open anomalies in the last 24 h." detail="Floats are within corridor bands." />}{query.hasNextPage && <button className="button secondary load-more" onClick={() => query.fetchNextPage()} disabled={query.isFetchingNextPage}>{query.isFetchingNextPage ? "Loading…" : "Load more"}</button>}</section>{selected ? <AnomalyDetail anomaly={selected} acknowledging={acknowledge.isPending} onAcknowledge={() => acknowledge.mutate(selected.id)} /> : <aside className="detail-placeholder"><ShieldAlert size={24}/><h2>Select an anomaly</h2><p>Its contributing signals, suggested action, and evidence-ready export will appear here.</p></aside>}</div>}</PageFrame>; }

function AnomalyDetail({ anomaly, onAcknowledge, acknowledging }: { anomaly: Anomaly; onAcknowledge: () => void; acknowledging: boolean }) { return <aside className="anomaly-detail"><p className="eyebrow">Evidence detail</p><h2>{anomaly.kind.replaceAll("_", " ")}</h2><div className="score-block"><span>Composite score</span><strong>{anomaly.score}<small>/100</small></strong></div><h3>Contributing signals</h3><dl>{Object.entries(anomaly.signals).map(([signal, value]) => <div key={signal}><dt>{signal}</dt><dd>{value}</dd></div>)}</dl><h3>Suggested human actions</h3><ul>{anomaly.suggestedActions.map((action) => <li key={action}>{action}</li>)}</ul><div className="detail-actions"><button className="button primary" onClick={onAcknowledge} disabled={acknowledging || Boolean(anomaly.acknowledgedAt)}><Check size={16}/>{anomaly.acknowledgedAt ? "Acknowledged" : acknowledging ? "Saving…" : "Acknowledge"}</button><button className="button secondary" disabled><Download size={16}/>Export JSON</button></div></aside>; }
