"use client";

import { useQuery } from "@tanstack/react-query";
import { BarChart3, CircleDollarSign, FlaskConical } from "lucide-react";
import { api } from "@/lib/api/client";
import { ApiUnavailable, EmptyState, LoadingState } from "@/components/ui/States";
import { PageFrame } from "../dashboard/page";

const number = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 });

export default function LiquidityPage() { const query = useQuery({ queryKey: ["liquidity"], queryFn: () => api.liquidity() }); return <PageFrame eyebrow="Provider context" title="Float, pressure, and corridor health" detail="All balances and service signals are supplied by the backend dataset. A corridor is never treated as executable liquidity.">{query.isLoading ? <LoadingState label="Loading float positions"/> : query.isError ? <ApiUnavailable onRetry={() => query.refetch()} /> : <LiquidityTable snapshots={query.data ?? []} />}</PageFrame>; }

function LiquidityTable({ snapshots }: { snapshots: Awaited<ReturnType<typeof api.liquidity>> }) { const corridors = [...new Set(snapshots.map((snapshot) => snapshot.corridor))]; return <div className="page-stack"><section className="corridor-chips">{corridors.map((corridor) => { const rows = snapshots.filter((snapshot) => snapshot.corridor === corridor); return <button key={corridor} className={rows.every((row) => row.healthy) ? "chip healthy" : "chip at-risk"}><i />{corridor}</button>; })}</section><section className="data-panel"><div className="liquidity-lead"><div><p className="eyebrow">Live positions</p><h2>Provider-level availability</h2></div><div className="sandbox-note"><FlaskConical size={17}/><span>What-if rebalancing is <strong>simulation only</strong> — never executed.</span></div></div>{snapshots.length ? <div className="table-wrap"><table className="standard-table"><thead><tr><th>Provider</th><th>Corridor</th><th>Available float</th><th>Pending</th><th>p95 SLA</th><th>Error rate</th><th>Health</th></tr></thead><tbody>{snapshots.map((item) => <tr key={`${item.providerId}-${item.corridor}-${item.ts}`}><td><CircleDollarSign size={15}/>{item.providerId}</td><td>{item.corridor}</td><td className="numeric">{number.format(item.floatUsd)}</td><td className="numeric">{number.format(item.pendingUsd)}</td><td>{Math.round(item.slaP95Ms)} ms</td><td>{(item.errorRate * 100).toFixed(2)}%</td><td><span className={`health-badge ${item.healthy ? "healthy" : "at-risk"}`}>{item.healthy ? "Within band" : "Needs review"}</span></td></tr>)}</tbody></table></div> : <EmptyState title="No liquidity positions are available." detail="The backend must return LiquiditySnapshot records for this view." />}</section><section className="simulation-card"><BarChart3/><div><p className="eyebrow">Sandbox reserved</p><h2>Model the effect before a human coordination decision</h2><p>The future simulation will calculate synthetic outcomes from backend supplied float, latency, and error-rate bands. It will never post a transfer request.</p></div><button className="button secondary" disabled>Simulate only — not executed</button></section></div>; }
